/**
 * Rakuten Ichiba Search Client
 *
 * Calls the server-side /api/rakuten-search endpoint which proxies
 * requests to Rakuten's API with proper Referer headers.
 *
 * Uses a fallback keyword strategy:
 * 1. producer + name + vintage (most specific)
 * 2. producer + name (without vintage)
 * 3. name only (stripped of common prefixes like "Chateau")
 * This ensures results even when Rakuten listings use Japanese names.
 */

export interface RakutenItem {
  itemName: string;
  itemPrice: number;
  itemUrl: string;       // Proper affiliate URL from Rakuten API
  shopName: string;
  imageUrl: string;
  reviewAverage: number;
  reviewCount: number;
}

export interface RakutenSearchResult {
  items: RakutenItem[];
  count: number;
}

/**
 * Strip common wine prefixes that may prevent Rakuten matches.
 * e.g. "Chateau Marquis de Terme" → "Marquis de Terme"
 */
function stripWinePrefixes(name: string): string {
  return name
    .replace(/^(Château|Chateau|Domaine|Maison|Bodega|Tenuta|Weingut|Casa)\s+/i, "")
    .trim();
}

/**
 * Build a prioritized list of search keywords from wine info.
 * Returns multiple candidates from most specific to least specific.
 */
export function buildRakutenKeywords(params: {
  producer?: string;
  name?: string;
  vintage?: string | number | null;
  country?: string;
}): string[] {
  const keywords: string[] = [];
  const producer = params.producer?.trim() || "";
  const name = params.name?.trim() || "";
  const vintage = params.vintage ? String(params.vintage) : "";

  // Primary name to use (producer, or name if different)
  const mainName = producer || name;
  const hasDistinctName = name && name !== producer;

  // 1. Full: producer + name + vintage
  if (mainName && vintage) {
    const parts = [mainName];
    if (hasDistinctName) parts.push(name);
    parts.push(vintage);
    keywords.push(parts.join(" "));
  }

  // 2. Without vintage: producer + name
  if (mainName) {
    const parts = [mainName];
    if (hasDistinctName) parts.push(name);
    keywords.push(parts.join(" "));
  }

  // 3. Stripped prefix + vintage (e.g. "Marquis de Terme 2022")
  const stripped = stripWinePrefixes(mainName);
  if (stripped && stripped !== mainName) {
    if (vintage) {
      keywords.push(`${stripped} ${vintage}`);
    }
    keywords.push(stripped);
  }

  // 4. Name only if different from producer
  if (hasDistinctName) {
    const strippedName = stripWinePrefixes(name);
    if (!keywords.includes(name)) keywords.push(name);
    if (strippedName !== name && !keywords.includes(strippedName)) {
      keywords.push(strippedName);
    }
  }

  // 5. Fallback: country + ワイン
  if (keywords.length === 0 && params.country) {
    keywords.push(`${params.country} ワイン`);
  }

  // Deduplicate
  return [...new Set(keywords)];
}

/**
 * Legacy single-keyword builder (kept for backward compatibility).
 */
export function buildRakutenKeyword(params: {
  producer?: string;
  name?: string;
  vintage?: string | number | null;
  country?: string;
}): string {
  const keywords = buildRakutenKeywords(params);
  return keywords[0] || "";
}

/**
 * Execute a single search against Rakuten API.
 */
async function searchOnce(keyword: string): Promise<RakutenSearchResult> {
  if (!keyword.trim()) return { items: [], count: 0 };

  try {
    const res = await fetch(
      `/api/rakuten-search?keyword=${encodeURIComponent(keyword)}`
    );

    if (!res.ok) {
      console.error("[rakuten] Search failed:", res.status);
      return { items: [], count: 0 };
    }

    return await res.json();
  } catch (err) {
    console.error("[rakuten] Search error:", err);
    return { items: [], count: 0 };
  }
}

/**
 * Search Rakuten Ichiba for wine products via server-side proxy.
 * Returns items with proper affiliate URLs generated by Rakuten's API.
 */
export async function searchRakutenWines(keyword: string): Promise<RakutenSearchResult> {
  return searchOnce(keyword);
}

/**
 * Search Rakuten with automatic fallback through multiple keyword candidates.
 * Tries each keyword in order until results are found.
 */
export async function searchRakutenWinesWithFallback(params: {
  producer?: string;
  name?: string;
  vintage?: string | number | null;
  country?: string;
}): Promise<RakutenSearchResult> {
  const keywords = buildRakutenKeywords(params);

  for (const kw of keywords) {
    console.log("[rakuten] Trying keyword:", kw);
    const result = await searchOnce(kw);
    if (result.items.length > 0) {
      console.log("[rakuten] Found", result.items.length, "items with:", kw);
      return result;
    }
  }

  console.log("[rakuten] No results found with any keyword");
  return { items: [], count: 0 };
}
