/**
 * Rakuten Ichiba Search Client
 *
 * Calls the server-side /api/rakuten-search endpoint which proxies
 * requests to Rakuten's API with proper Referer headers.
 */

export interface RakutenItem {
  itemName: string;
  itemPrice: number;
  itemUrl: string;       // Proper affiliate URL from Rakuten API
  shopName: string;
  imageUrl: string;
  reviewAverage: number;
  reviewCount: number;
}

export interface RakutenSearchResult {
  items: RakutenItem[];
  count: number;
}

/**
 * Build a search keyword from wine info.
 */
export function buildRakutenKeyword(params: {
  producer?: string;
  name?: string;
  vintage?: string | number | null;
  country?: string;
}): string {
  const parts: string[] = [];

  if (params.producer) parts.push(params.producer);
  if (params.name && params.name !== params.producer) parts.push(params.name);
  if (params.vintage) parts.push(String(params.vintage));

  // Fallback: if no producer/name, use country + "ワイン"
  if (parts.length === 0 && params.country) {
    parts.push(params.country);
    parts.push("ワイン");
  }

  return parts.join(" ");
}

/**
 * Search Rakuten Ichiba for wine products via server-side proxy.
 * Returns items with proper affiliate URLs generated by Rakuten's API.
 */
export async function searchRakutenWines(keyword: string): Promise<RakutenSearchResult> {
  if (!keyword.trim()) return { items: [], count: 0 };

  try {
    const res = await fetch(
      `/api/rakuten-search?keyword=${encodeURIComponent(keyword)}`
    );

    if (!res.ok) {
      console.error("[rakuten] Search failed:", res.status);
      return { items: [], count: 0 };
    }

    return await res.json();
  } catch (err) {
    console.error("[rakuten] Search error:", err);
    return { items: [], count: 0 };
  }
}
